### ISSUE TITLE
Add plotnine to terra-jupyter-python

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/terra-docker#126]
[plotnine](https://github.com/has2k1/plotnine) is an implementation of a grammar of graphics in Python, it is based on [ggplot2](https://github.com/tidyverse/ggplot2).

Having this available in terra-jupyter-python would make it such that the code for R and Python notebooks in Terra can look similar and decrease the cognitive load on researchers when going back-and-forth between the two languages.

Note that the [AoU Dockerfile](https://github.com/DataBiosphere/terra-docker/blob/master/terra-jupyter-aou/Dockerfile) adds plotnine.

**Comment by Qi77Qi** [comment]
think @deflaux 's PR has already addressed this...
