### ISSUE TITLE
Remove obsolete Python package enum34

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/terra-docker#175]
By default, use the standard library enum module instead. 

For more detail, please see https://stackoverflow.com/a/45716067/4138705

**Comment by rtitle** [comment]
This is merged, it should show up in Terra UI after the release next week.

**Comment by deflaux** [comment]
thanks!

**Comment by deflaux** [comment]
This obsolete Python package was still getting pulled into current images due to a dependency on an old version of pymc3.
