### ISSUE TITLE
GPUs, Terra image builds, and TF >=2.5

### ISSUE THREAD

**Issue by amygdala** [DataBiosphere/terra-docker#244]
Creating this issue for discussion. (I’m on the Terra solutions team at Verily).
It’s a known issue that the Terra images (using the `gcr.io/deeplearning-platform-release/base-cu110:latest` base image) don’t support >=TF 2.5 with GPUs due to a CUDA library mismatch.
I noticed that GCP notebooks, *which use the same base image*, do support >=TF 2.5 with GPUs where the Terra builds do not.

I did a bit of digging and I believe the reason for this is that the `gcr.io/deeplearning-platform-release/tf2-gpu.2-6` images etc. (which use the same base image above) do their own builds of TF from source, via `bazel`, using the CUDA 11.0 libs, rather than doing a `pip install`.    

The TF release notes indicate that from 2.5 onwards, the TF team’s builds (as you’d get from `pip`) are built using the CUDA 11.2 libs.  So, the GCP notebook team’s build from source, using the 11.0 libs, is key to why their images work for TF >=2.5. 
The GCP notebook team does have a bug in to update to using the 11.2 libs, but it’s just a placeholder and may not see movement soon.

We could just document this well and wait for the GCP notebook team to support CUDA 11.2. 
However, I suspect that many people won’t read the docs, will want to use TF >=2.5 and will probably attempt to update via `pip install`  without realizing that it will remove their use of GPUs.  

It might be worth considering **using the [GCP Notebooks images](https://cloud.google.com/deep-learning-containers/docs/choosing-container) as Terra base images**.  These images have many useful ML and data science-related libs installed in addition to the ML frameworks.
If we could get this working it would let us piggyback on the GCP Notebook team’s maintenance and testing of all the libraries that they install on these images, and their dependencies— basically offloading all that work.
To do this this would presumably require overriding their Jupyter config with the Terra Jupyter setup as the last steps in a Terra Dockerfile, probably `terra-jupyter-python`.

Would this approach— using the GCP notebook images rather than their base image as a starting point— be worth trying?
(A related question, that  I haven’t checked yet, is whether there are similar issues with other ML frameworks like PyTorch, but I suspect there are.  We could provide a set of images, based on the GCP notebook images, to choose from.)

/cc @deflaux

**Comment by amygdala** [comment]
One more comment: 
A third option — in addition to documenting the restriction or leveraging the GCP notebook images — would be to build TF from source yourself using the 11.0 libraries, same as the Notebooks team is doing.

**Comment by Qi77Qi** [comment]
@amygdala thanks for looking into this. We should definitely document this limitation. I'll ping our user education team about this.

> It might be worth considering using the GCP Notebooks images as Terra base images. These images have many useful ML and data science-related libs installed in addition to the ML frameworks.
We're using `gcr.io/deeplearning-platform-release/base-cu110`, which is in the list of the page you linked. Or are you suggesting some one image?

Btw, are you on Terra slack? it's probably easier to have back&forth discussion over there

**Comment by amygdala** [comment]
Thanks-- I was referring to `gcr.io/deeplearning-platform-release/tf2-gpu.2-6` and similar, which would obviate issues like the CUDA library mismatch I described, and would offload a lot of the ongoing library installation & dependency maintenance work to the GCP Notebooks team, and also make it straightforward to support different ML frameworks.  But of course adding the Terra notebook layers to those images— instead of the base image you're using now– might be more complex.

Discussing on Slack sounds like a good idea.  I just joined: https://terra-bio.slack.com — is that the right one?

**Comment by Qi77Qi** [comment]
@amygdala yea, `https://terra-bio.slack.com` is the one.

> I was referring to gcr.io/deeplearning-platform-release/tf2-gpu.2-6
As mentioned in the previous comment, the original reason for choosing `base-cu` was to reduce image size. I'll bring to the team and revisit this

**Comment by rtitle** [comment]
Just to circle back, as of this PR (https://github.com/DataBiosphere/terra-docker/pull/251) we are now deriving from gcr.io/deeplearning-platform-release/tf2-gpu.2-6 and support TensorFlow 2.6. I have done some local testing -- working now to integrate this into Leo/Terra proper.

**Comment by amygdala** [comment]
It looks like the update to the TF 2.7 base image fixed this issue!  Thank you.  Closing this.
