### ISSUE TITLE
issues with `pip install` when building library from source for `terra-jupyter-gatk` img 

### ISSUE THREAD

**Issue by amygdala** [DataBiosphere/terra-docker#285]
We're seeing issues with `pip install` for the `terra-jupyter-gatk` image when it's necessary to build the library from source.  

It appears that `PIP_TARGET` is set when `docker exec` is run on the GCE instance: `https://github.com/DataBiosphere/leonardo/search?q=PIP_TARGET`
Whenever we run `pip`, it interprets the environment variable `PIP_TARGET` as the value for the` --home` flag. https://github.com/pypa/pip/issues/8438#issuecomment-674420308
BUT . . . whenever pip tries to install any packages from source, it passes flag `--prefix `and those flags cannot be used together.

By unsetting `PIP_TARGET` for an installation, we can work around the issue. e.g.: 

`!unset PIP_TARGET ; pip install -U docstring-parser==0.13`

Nicole and I created a notebook to demo the issue: https://app.terra.bio/#workspaces/fc-product-demo/try-saturn/notebooks/launch/pip_install_issues.ipynb
The notebook html is attached in case it's useful.
[pip_install_issues.html.zip](https://github.com/DataBiosphere/terra-docker/files/7747532/pip_install_issues.html.zip)

**Other images may have this same issue**, but we haven't tested yet.
Given the workaround, it's not urgent, but other customers are presumably hitting this as well. (I'll send an email with a bit more after the holidays).

/cc @deflaux

**Comment by deflaux** [comment]
I updated our tests to more closely reflect the pip environment we have in production. I then added a test to demonstrate this issue https://github.com/DataBiosphere/terra-docker/pull/286. You can see from the GitHub action test artifacts that the test fails, as expected. I've commented out the final assertion for now, and we can uncomment that assertion after this issue is fixed.

**Comment by Qi77Qi** [comment]
@amygdala @deflaux think this is resolved with https://github.com/DataBiosphere/leonardo/pull/2518....
